const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');const path=require('node:path');
class ApiError extends Error {constructor(status,detail){super(detail);this.status=status;this.detail=detail;}}
function load(api={}){const source=fs.readFileSync(path.join(__dirname,'../src/lib/invoice-documents.ts'),'utf8');const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;const exports={};vm.runInNewContext(js,{exports,require:()=>({api,ApiError})});return exports;}
const plain=x=>JSON.parse(JSON.stringify(x));
test('optional purchase invoice fields serialize explicit clears',()=>{assert.deepEqual(plain(load().invoicePhaseDFields('','  ')),{purchaseOrderId:null,invoiceType:null});});
test('unchanged Phase D fields are omitted on header edits',()=>{assert.deepEqual(plain(load().invoicePhaseDFields('po','CUSTOM_TYPE',{purchaseOrderId:'po',invoiceType:'CUSTOM_TYPE'})),{});assert.deepEqual(plain(load().invoicePhaseDFields('','',{purchaseOrderId:'po',invoiceType:'CUSTOM_TYPE'})),{purchaseOrderId:null,invoiceType:null});});
test('missing persisted PO and invoice type are detected',()=>{const errors=load().invoiceSaveMismatches({purchaseOrderId:'po',invoiceType:'CUSTOM_TYPE'},{details:[]});assert.equal(errors.join(','),'Purchase Order,Tipe Invoice');});
test('ignored unit saves are detected including repeated items',()=>{const details=[{barangId:'b',satuanId:'u',qty:1,harga:10},{barangId:'b',satuanId:'v',qty:1,harga:10}];assert.equal(load().invoiceSaveMismatches({details},{details:details.map(d=>({...d,satuanId:null}))}).length,1);assert.equal(load().invoiceSaveMismatches({details},{details:[...details].reverse()}).length,0);});
test('empty optional units and equivalent numeric response values match',()=>{assert.equal(load().invoiceSaveMismatches({details:[{barangId:'b',qty:1,harga:10,satuanId:null}]},{details:[{barangId:'b',qty:'1',harga:'10.00'}]}).length,0);});
test('create disables auto posting and preserves ID before mismatch reporting',async()=>{let request,savedId;const m=load({post:async(url,body)=>{request=body;return {id:'existing',noForm:'PINV-1',details:[]};}});const result=await m.createPurchaseInvoice({invoiceType:'CUSTOM_TYPE',details:[],autoPostJurnal:true},saved=>{savedId=saved.id;});assert.equal(request.autoPostJurnal,false);assert.equal(savedId,'existing');assert.equal(result.mismatches.length,1);});
test('failed create does not signal a saved document',async()=>{let called=false;await assert.rejects(load({post:async()=>{throw new ApiError(400,'No faktur sudah digunakan');}}).createPurchaseInvoice({},()=>{called=true;}),/sudah/);assert.equal(called,false);});
test('duplicate invoice field errors require backend 400 and preserve its message',()=>{const m=load();assert.equal(m.duplicateInvoiceMessage(new ApiError(400,'No faktur ABC sudah digunakan supplier')), 'No faktur ABC sudah digunakan supplier');assert.equal(m.duplicateInvoiceMessage(new ApiError(400,'Gudang wajib diisi')),null);assert.equal(m.duplicateInvoiceMessage(new ApiError(500,'Duplicate no_faktur')),null);});
test('type suggestions use backend values across pages without a fixed enum',async()=>{const urls=[];const pages=[{total:3,data:[{invoiceType:'CUSTOM_TYPE'},{invoiceType:null}]},{total:3,data:[{invoiceType:'CUSTOM_TYPE'}]}];const values=await load({get:async url=>{urls.push(url);return pages.shift();}}).loadInvoiceTypeSuggestions();assert.equal(values.join(','),'CUSTOM_TYPE');assert.match(urls[1],/skip=2/);});
test('type loading reports network and incomplete pagination errors',async()=>{await assert.rejects(load({get:async()=>{throw Error('offline');}}).loadInvoiceTypeSuggestions(),/offline/);await assert.rejects(load({get:async()=>({total:1,data:[]})}).loadInvoiceTypeSuggestions(),/belum lengkap/);});
