const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');const path=require('node:path');
function load(file='return-documents',api={}){const source=fs.readFileSync(path.join(__dirname,'../src/lib/'+file+'.ts'),'utf8');const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;const exports={};vm.runInNewContext(js,{exports,require:()=>({api}),URLSearchParams});return exports;}
const invoice={id:'inv',details:[{id:'line1',barangId:'same',harga:'100.50',qty:5},{id:'line2',barangId:'same',harga:'200.00',qty:2}]};
test('same item on distinct invoice rows retains its own source price and trace',()=>{const details=load().salesReturnDetails(invoice,{line1:'1',line2:'2'});assert.equal(details[0].harga,100.5);assert.equal(details[1].harga,200);assert.equal(details[1].salesInvoiceDetailId,'line2');assert.equal(details[1].subTotal,400);});
test('unselected rows do not become returns and at least one selection is required',()=>{assert.equal(load().salesReturnDetails(invoice,{line1:'0',line2:'1'}).length,1);assert.throws(()=>load().salesReturnDetails(invoice,{line1:'',line2:'0'}),/minimal satu/);});
test('invalid, negative and fractional quantities are rejected',()=>{for(const qty of ['abc','-1','0.5','Infinity'])assert.throws(()=>load().salesReturnDetails(invoice,{line1:qty}),/bilangan bulat positif/);});
test('selections from a previous invoice cannot leak into the next payload',()=>{assert.throws(()=>load().salesReturnDetails(invoice,{oldLine:'1'}),/tidak berasal/);});
test('source prices must be valid but a zero source price remains zero',()=>{for(const harga of [null,'','abc',-1])assert.throws(()=>load().salesReturnDetails({details:[{...invoice.details[0],harga}]},{line1:'1'}),/Harga invoice sumber/);assert.equal(load().salesReturnDetails({details:[{...invoice.details[0],harga:0}]},{line1:'1'})[0].harga,0);});
test('returnable quantity remains a server decision, without an invented local balance',()=>{assert.equal(load().salesReturnDetails(invoice,{line1:'6'})[0].qty,6);});
test('backend loss of source link or price is detected, response ordering is ignored',()=>{const m=load();const details=m.salesReturnDetails(invoice,{line1:'1',line2:'1'});assert.equal(m.salesReturnSaveMismatches(details,{details:[...details].reverse()}).length,0);assert.equal(m.salesReturnSaveMismatches(details,{details:details.map(d=>({...d,salesInvoiceDetailId:null}))}).length,1);assert.equal(m.salesReturnSaveMismatches(details,{details:details.map(d=>({...d,harga:0}))}).length,1);});
test('create sends false auto-post and preserves saved ID before detecting incomplete response',async()=>{let payload,id;const m=load('return-documents',{post:async(url,body)=>{assert.equal(url,'/penjualan/sales-retur');payload=body;return{id:'saved',details:[]};}});const result=await m.createSalesReturn({autoPostJurnal:true,details:[{barangId:'b',salesInvoiceDetailId:'l',harga:10,qty:1}]},saved=>{id=saved.id;});assert.equal(payload.autoPostJurnal,false);assert.equal(id,'saved');assert.equal(result.mismatches.length,1);});
test('failed create never calls the saved callback',async()=>{let saved=false;await assert.rejects(load('return-documents',{post:async()=>{throw Error('Over-return');}}).createSalesReturn({details:[]},()=>{saved=true;}),/Over-return/);assert.equal(saved,false);});
test('both return workflows preserve full over-return and source-price errors in modals',()=>{const m=load('delivery-receipt');for(const doc of ['sales_retur','purchase_retur'])for(const detail of ['Over-return: qty invoice 5, sudah diretur 4, diminta 2, selisih 1','Harga retur (200) tidak boleh berbeda dari harga invoice sumber (100) untuk barang B']){const result=m.describeStockOperationError(doc,detail);assert.equal(result.presentation,'modal');assert.equal(result.detail,detail);}assert.equal(m.describeStockOperationError('sales_retur','Gudang tidak ditemukan').presentation,'toast');assert.equal(m.describeStockOperationError('sales_order','Over-return'),null);});
