const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');const path=require('node:path');
function load(api={}) {const source=fs.readFileSync(path.join(__dirname,'../src/lib/delivery-receipt.ts'),'utf8');const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;const exports={};vm.runInNewContext(js,{exports,require:()=>({api}),URLSearchParams});return exports;}
const line={barangId:'b',satuanId:'u',qty:'1'};
test('stock lines require a selected item and its unit',()=>{const m=load();assert.match(m.stockLineError([]),/Minimal/);assert.match(m.stockLineError([{...line,satuanId:''}]),/satuan/);assert.match(m.stockLineError([line,{...line,barangId:''}]),/Baris 2/);});
test('stock qty rejects empty, zero, negative, fractional and nonnumeric values',()=>{for(const qty of ['',0,-1,1.5,'abc','Infinity']) assert.match(load().stockLineError([{...line,qty}]),/minimal 1/);});
test('valid stock lines tolerate unused placeholder rows',()=>{assert.equal(load().stockLineError([line,{barangId:'',satuanId:'',qty:1}]),null);});
test('actual backend GRNI wording opens guidance and preserves complete detail',()=>{const detail='Akun GRNI (PENERIMAAN_DALAM_PROSES) belum di-configure. Goods Receipt wajib menggunakan GRNI architecture. Configure via PUT /master/setting-akun/PENERIMAAN_DALAM_PROSES.';const error=load().describeStockOperationError('penerimaan_barang',detail);assert.equal(error.presentation,'modal');assert.equal(error.guidance,'grni');assert.equal(error.detail,detail);});
test('overdelivery modal preserves backend quantities and item details',()=>{const detail='Over-delivery: Barang Buku, qty pesanan 10, sudah dikirim 9, diminta 2';const error=load().describeStockOperationError('pengiriman_barang',detail);assert.equal(error.presentation,'modal');assert.equal(error.detail,detail);});
test('warehouse and qty failures offer toast guidance',()=>{const m=load();for(const doc of ['pengiriman_barang','penerimaan_barang']){assert.match(m.describeStockOperationError(doc,'Gudang wajib diisi').hint,/pilih gudang/);assert.match(m.describeStockOperationError(doc,'Qty pengiriman harus > 0').hint,/nol atau negatif/);}});
test('unrelated workflows and other backend errors retain normal handling',()=>{const m=load();assert.equal(m.describeStockOperationError('sales_order','Over-delivery'),null);const error=m.describeStockOperationError('penerimaan_barang','Supplier tidak sama dengan PO');assert.equal(error.presentation,'toast');assert.equal(error.detail,'Supplier tidak sama dengan PO');});
test('empty supplier does not fetch optional invoices',async()=>{const options=await load({get:()=>{throw Error('unexpected request');}}).loadReceiptInvoiceOptions('');assert.equal(options.length,0);});
test('invoice choices paginate and exclude posted or finished invoices',async()=>{const urls=[];const pages=[{total:4,data:[{id:'a',status:'DRAFT'},{id:'b',status:'DIPROSES',jurnalUmumId:'j'}]},{total:4,data:[{id:'c',status:'SELESAI'},{id:'d',status:'DIPROSES'}]}];const rows=await load({get:async url=>{urls.push(url);return pages.shift();}}).loadReceiptInvoiceOptions('supplier & one');assert.equal(rows.map(x=>x.id).join(','),'a,d');assert.match(urls[1],/skip=2/);assert.equal(new URL(urls[0],'https://local.test').searchParams.get('supplier_id'),'supplier & one');});
test('invoice load failures propagate instead of masquerading as empty choices',async()=>{await assert.rejects(load({get:async()=>{throw Error('offline');}}).loadReceiptInvoiceOptions('s'),/offline/);await assert.rejects(load({get:async()=>({data:[],total:1})}).loadReceiptInvoiceOptions('s'),/belum lengkap/);});
